# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# A lot of this came from 
# https://dev.to/mpocock1/how-to-cache-nodemodules-in-github-actions-with-yarn-24eh
name: Node.js CI

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # Must match production node environment on Heroku
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Cache `node_modules`
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    
    - name: Yarn Install
      run: yarn install
    
    - name: Lint with Prettier
      run: yarn run lint
    
    - name: Build with NextJS
      run: yarn run build
    
    - name: Run Unit Tests with (Unknown)
      run: yarn run test:unit
    
    - name: Run End to End Tests with Cypress
      run: yarn run cypress
